### ISSUE TITLE
error when 'from xfinity_usage import XfinityUsage' from a client module

### ISSUE THREAD

**Issue by billimek** [jantman/xfinity-usage#10]
**I have a PR to resolve this that will be submitted shortly**

### Version

2.0.0

### Installation Method

`pip install xfinity-usage` followed by 
`from xfinity_usage import XfinityUsage` in a python module

### Supporting Software Versions

Python 2.7.14
Python 3.6.3
pip 9.0.1

### Actual Output

```
Traceback (most recent call last):
  File "InfluxdbComcast.py", line 10, in <module>
    from xfinity_usage import XfinityUsage
ImportError: cannot import name 'XfinityUsage'
```

### Expected Output

Successfully import XfinityUsage

**Comment by billimek** [comment]
Using `from xfinity_usage.xfinity_usage import XfinityUsage` may work, checking now.

**Comment by billimek** [comment]
`from xfinity_usage.xfinity_usage import XfinityUsage` works for importing, so no issue - closing!

**Comment by jantman** [comment]
@billimek Sorry for the confusion, I'll cut a PR to update the README with an example of Python usage.

Ironically the tox failure in #11 was caused by the reason I don't do package-level imports in ``__init__.py`` unless I can help it; importing from ``xfinity_usage.xfinity_usage`` in that context causes resolution of all of its dependencies, which includes selenium... which isn't present in the pristine virtualenv that tox is run in to build the package.
